# Generated by Django 6.0.6 on 2026-07-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('situation', models.IntegerField(choices=[(1, 'alerta'), (2, 'atencao'), (3, 'mobilizacao'), (4, 'normalidade')], default=4)),
                ('type', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(max_length=22)),
            ],
        ),
    ]
