# Generated by Django 6.0.6 on 2026-07-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0001_initial'),
        ('occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occorrences', to='addressing.neighborhood'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='type',
            field=models.IntegerField(choices=[(1, 'alagamento'), (2, 'chuvas_intensas'), (3, 'enxurrada'), (4, 'inundacao')], default=1),
        ),
    ]
