# Generated by Django 6.0.6 on 2026-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0002_alter_occurrence_neighborhood_alter_occurrence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='situation',
            field=models.IntegerField(choices=[(1, 'Alerta'), (2, 'Atenção'), (3, 'Mobilização'), (4, 'Normalidade')], default=4),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='type',
            field=models.IntegerField(choices=[(1, 'Alagamento'), (2, 'Chuvas Intensas'), (3, 'Enxurrada'), (4, 'Inundação')], default=1),
        ),
    ]
