# Generated by Django 6.0.6 on 2026-07-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occurrences', '0003_alter_occurrence_situation_alter_occurrence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
