# Generated by Django 6.0.6 on 2026-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0001_initial'),
        ('occurrences', '0004_alter_occurrence_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='neighborhood',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='situation',
            field=models.IntegerField(choices=[(1, 'Alerta'), (2, 'Atenção'), (3, 'Emergência'), (4, 'Normalidade')], default=4),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='neighborhood',
            field=models.ManyToManyField(related_name='occorrences', to='addressing.neighborhood'),
        ),
    ]
