# Generated by Django 6.0.6 on 2026-07-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addressing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flood_Point_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('possibility', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(db_index=True)),
                ('props', models.JSONField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressing.city')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addressing.neighborhood')),
            ],
        ),
    ]
