# Generated by Django 5.2.16 on 2026-07-21 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_primary_neighborhoods(apps, schema_editor):
    FloodPoint = apps.get_model("flood_point_registering", "Flood_Point_Register")
    FloodPointNeighborhood = apps.get_model(
        "flood_point_registering", "FloodPointNeighborhood"
    )
    batch = []
    for flood_point_id, neighborhood_id in FloodPoint.objects.exclude(
        neighborhood_id__isnull=True
    ).values_list("id", "neighborhood_id").iterator(chunk_size=1000):
        batch.append(FloodPointNeighborhood(
            flood_point_id=flood_point_id,
            neighborhood_id=neighborhood_id,
            is_primary=True,
            relation="LEGACY_PRIMARY",
            resolution_method="LEGACY_FK",
            review_status="automatic",
        ))
        if len(batch) >= 1000:
            FloodPointNeighborhood.objects.bulk_create(batch, batch_size=1000)
            batch.clear()
    if batch:
        FloodPointNeighborhood.objects.bulk_create(batch, batch_size=1000)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0025_referencebaserelease_referencebasereleaseaudit_and_more'),
        ('flood_point_registering', '0008_backfill_spatial_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodPointNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('relation', models.CharField(blank=True, max_length=32)),
                ('intersection_area_m2', models.FloatField(blank=True, null=True)),
                ('footprint_fraction', models.FloatField(blank=True, null=True)),
                ('resolution_method', models.CharField(max_length=80)),
                ('review_status', models.CharField(choices=[('automatic', 'Automatico'), ('reviewed', 'Revisado'), ('rejected', 'Rejeitado')], default='automatic', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flood_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood_links', to='flood_point_registering.flood_point_register')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flood_point_links', to='addressing.neighborhood')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flood_point_neighborhoods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flood_point_register',
            name='neighborhoods',
            field=models.ManyToManyField(related_name='flood_points', through='flood_point_registering.FloodPointNeighborhood', to='addressing.neighborhood'),
        ),
        migrations.RunPython(backfill_primary_neighborhoods, noop_reverse),
        migrations.AddIndex(
            model_name='floodpointneighborhood',
            index=models.Index(fields=['neighborhood', 'is_primary'], name='flood_point_neighbo_96321d_idx'),
        ),
        migrations.AddConstraint(
            model_name='floodpointneighborhood',
            constraint=models.UniqueConstraint(fields=('flood_point', 'neighborhood'), name='uniq_flood_point_neighborhood'),
        ),
        migrations.AddConstraint(
            model_name='floodpointneighborhood',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('flood_point',), name='uniq_primary_neighborhood_per_flood_point'),
        ),
        migrations.AddConstraint(
            model_name='floodpointneighborhood',
            constraint=models.CheckConstraint(condition=models.Q(('footprint_fraction__isnull', True), models.Q(('footprint_fraction__gte', 0), ('footprint_fraction__lte', 1)), _connector='OR'), name='flood_neighborhood_fraction_range'),
        ),
        migrations.AddConstraint(
            model_name='floodpointneighborhood',
            constraint=models.CheckConstraint(condition=models.Q(('intersection_area_m2__isnull', True), ('intersection_area_m2__gte', 0), _connector='OR'), name='flood_neighborhood_area_nonnegative'),
        ),
    ]
