# Generated by Django 5.2.5 on 2026-05-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_profile_picture"),
    ]

    operations = []
