"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Importações administrativas aceitam apenas arquivos previamente colocados
# neste diretório; não há upload arbitrário pela API.
GEODATA_IMPORT_ROOT = BASE_DIR / "data" / "geodata"
GEODATA_IMPORT_MAX_BYTES = 50 * 1024 * 1024
ADDRESSING_RESOLVE_RADIUS_METERS = 200
ADDRESSING_RESOLVE_MAX_RADIUS_METERS = 1000


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0") == "1"

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    # Subdomínios de fexcompany.me
    "https://*.fexcompany.me",
    # Subdomínios de fabricadesoftware.ifc.edu.br
    "https://*.fabricadesoftware.ifc.edu.br",
    # Front-end local
    "http://localhost:8000",
    "http://localhost:5173",
    "http://localhost:3000",
    "https://*.michalski.app",

]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Frontend em desenvolvimento
    "http://localhost:3000",
    "https://aqua.fabricadesoftware.ifc.edu.br",
    "https://*.fabricadesoftware.ifc.edu.br",
    "https://*.michalski.app",

]


# Application definition

INSTALLED_APPS = [
    "django.contrib.gis",
    "core.flood_impact",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "django_celery_beat",
    "core",
    "core.users",
    "core.weather",
    "core.occurrences",
    "core.forecast",
    "core.flood_camera_monitoring",
    "core.uploader",
    "core.addressing",
    "core.flood_point_registering",
    "core.donate",
    "core.blog",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # CORS must be as high as possible, especially before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = os.getenv("DJANGO_ROOT_URLCONF", "config.urls")

# The development gateway remains lightweight and proxies only flood-specific
# routes to the optional flood service. Production uses direct views.
FLOOD_CAMERA_API_MODE = os.getenv("FLOOD_CAMERA_API_MODE", "direct").strip().lower()
if FLOOD_CAMERA_API_MODE not in {"direct", "proxy"}:
    raise ImproperlyConfigured(
        "FLOOD_CAMERA_API_MODE must be either 'direct' or 'proxy'"
    )

FLOOD_CAMERA_SERVICE_URL = os.getenv(
    "FLOOD_CAMERA_SERVICE_URL", "http://flood-api:8091"
).rstrip("/")
FLOOD_CAMERA_PROXY_CONNECT_TIMEOUT_SECONDS = float(
    os.getenv("FLOOD_CAMERA_PROXY_CONNECT_TIMEOUT_SECONDS", "2")
)
FLOOD_CAMERA_PROXY_READ_TIMEOUT_SECONDS = float(
    os.getenv("FLOOD_CAMERA_PROXY_READ_TIMEOUT_SECONDS", "120")
)
FLOOD_CAMERA_DEDICATED_QUEUE = (
    os.getenv("FLOOD_CAMERA_DEDICATED_QUEUE", "0") == "1"
)

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Prefer DATABASE_URL; if missing, build from POSTGRES_* env vars; else fallback to sqlite
_db_url = os.getenv("DATABASE_URL")
if not _db_url:
    _pg_user = os.getenv("POSTGRES_USER")
    _pg_pass = os.getenv("POSTGRES_PASSWORD")
    _pg_db = os.getenv("POSTGRES_DB")
    _pg_host = os.getenv("POSTGRES_HOST", "db")
    _pg_port = os.getenv("POSTGRES_PORT", "5432")
    if _pg_user and _pg_pass and _pg_db:
        _db_url = f"postgresql://{_pg_user}:{_pg_pass}@{_pg_host}:{_pg_port}/{_pg_db}"

DATABASES = {
    "default": dj_database_url.config(
        default=_db_url or f"sqlite:///{BASE_DIR / 'db.sqlite3'}"
    )
}
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"]["ENGINE"] = "django.contrib.gis.db.backends.postgis"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where collectstatic will gather static files (required for builds/production)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

UPLOADER_IMAGE_MAX_BYTES = int(
    os.getenv("UPLOADER_IMAGE_MAX_BYTES", str(10 * 1024 * 1024))
)
UPLOADER_VIDEO_MAX_BYTES = int(
    os.getenv("UPLOADER_VIDEO_MAX_BYTES", str(500 * 1024 * 1024))
)

# Optional deterministic demo stream. The default keeps demo endpoints
# disabled until the Compose `demo` profile is explicitly enabled.
DEMO_ENABLED = os.getenv("DEMO_ENABLED", "0") == "1"
DEMO_CONTROL_TOKEN = os.getenv("DEMO_CONTROL_TOKEN", "")
DEMO_SCENARIO_PATH = os.getenv(
    "DEMO_SCENARIO_PATH", "/demo-assets/scenario.json"
)
DEMO_WORK_DIR = os.getenv("DEMO_WORK_DIR", "/tmp/aqua-demo-stream")
DEMO_PREDICTION_CACHE_SECONDS = int(
    os.getenv("DEMO_PREDICTION_CACHE_SECONDS", "30")
)
DEMO_STREAM_INTERNAL_URL = os.getenv(
    "DEMO_STREAM_INTERNAL_URL", "http://demo-stream:8089"
).rstrip("/")
DEMO_STREAM_MEDIA_INTERNAL_BASE_URL = os.getenv(
    "DEMO_STREAM_MEDIA_INTERNAL_BASE_URL", "http://demo-stream:8088"
).rstrip("/")
DEMO_STREAM_PUBLIC_URL = os.getenv(
    "DEMO_STREAM_PUBLIC_URL", "http://localhost:8088/hls/playlist.m3u8"
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Redis / Celery configuration (allow overrides from env)
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://redis:6379/1")

# Uma leitura operacional deixa de representar o estado atual após dez minutos.
FLOOD_ANALYSIS_STALE_SECONDS = int(
    os.getenv("FLOOD_ANALYSIS_STALE_SECONDS", "600")
)

# Optional: simple beat schedule to validate the worker periodically
from celery.schedules import crontab  # type: ignore

CELERY_BEAT_SCHEDULE = {
    "flood-analyze-all-cameras": {
        "task": "core.flood_camera_monitoring.infra.tasks.analyze_all_cameras_task",
        "schedule": 300.00,
    },
}

# Only development services that explicitly opt into Flood Monitoring route
# its work to the dedicated worker. Production retains the established queue.
if FLOOD_CAMERA_DEDICATED_QUEUE:
    CELERY_TASK_ROUTES = {
        "core.flood_camera_monitoring.*": {"queue": "flood_camera"},
    }

# Logging: ensure our modules and Celery log to console at INFO level
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        }
    },
    "loggers": {
        "django": {"handlers": ["console"], "level": "INFO"},
        "celery": {"handlers": ["console"], "level": "INFO"},
        # Parent logger for all flood monitoring modules
        "core.flood_camera_monitoring": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Custom: Public link to camera installation instructions/UI
# Read from environment variable CAMERA_INSTALL_URL; defaults to empty string if not set
CAMERA_INSTALL_URL = os.getenv("CAMERA_INSTALL_URL", "")

# Redis URL dedicated for application cache (separate DB from Celery broker/results).
# Defaults to DB 2 on the same Redis host.
REDIS_CACHE_URL = os.getenv("REDIS_CACHE_URL", "redis://redis:6379/2")

# Django REST Framework
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "config.pagination.DefaultPageNumberPagination",
    # Default page size, can be overridden via ?page_size= and capped by paginator
    "PAGE_SIZE": int(os.getenv("API_PAGE_SIZE", "20")),
    # Use SimpleJWT with custom user resolver
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "core.users.presentation.auth.AppJWTAuthentication",
    ),
}

# djangorestframework-simplejwt configuration
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", "60"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": os.getenv("JWT_ALGORITHM", "HS256"),
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}
