# Generated by Django 6.0.6 on 2026-07-03 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='addressing__name_92704e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='addressing.city')),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=120)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to='addressing.city')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='neighborhoods', to='addressing.region')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(default='Brazil', max_length=120)),
                ('zipcode', models.CharField(blank=True, max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='addressing.neighborhood')),
            ],
            options={
                'indexes': [models.Index(fields=['city'], name='addressing__city_ee06f2_idx'), models.Index(fields=['zipcode'], name='addressing__zipcode_804c21_idx'), models.Index(fields=['neighborhood'], name='addressing__neighbo_949d5a_idx'), models.Index(fields=['latitude', 'longitude'], name='addressing__latitud_7a5597_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['city'], name='addressing__city_bcd318_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['city'], name='addressing__city_8d0354_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['name'], name='addressing__name_67757a_idx'),
        ),
        migrations.AddIndex(
            model_name='neighborhood',
            index=models.Index(fields=['region'], name='addressing__region__c292cf_idx'),
        ),
    ]
