# Generated by Django 5.2.16 on 2026-07-21 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressing', '0024_canonicalize_catalog_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBaseRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('staged', 'Preparado'), ('validated', 'Validado'), ('promoting', 'Em promocao'), ('active', 'Ativo'), ('superseded', 'Substituido'), ('rejected', 'Rejeitado'), ('failed', 'Falhou')], db_index=True, default='staged', max_length=16)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('archive_sha256', models.CharField(max_length=64, unique=True)),
                ('manifest', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('failure_detail', models.TextField(blank=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_base_releases', to='addressing.geodatadataset')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceBaseReleaseAudit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('import', 'Importacao'), ('promote', 'Promocao'), ('rollback', 'Rollback'), ('reject', 'Rejeicao'), ('fail', 'Falha')], max_length=16)),
                ('from_revision', models.CharField(blank=True, max_length=160)),
                ('to_revision', models.CharField(max_length=160)),
                ('expected_revision', models.CharField(blank=True, max_length=160)),
                ('justification', models.TextField()),
                ('succeeded', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='addressing.referencebaserelease')),
            ],
        ),
        migrations.AddIndex(
            model_name='referencebaserelease',
            index=models.Index(fields=['status', 'revision'], name='addressing__status_3514b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='referencebaserelease',
            constraint=models.UniqueConstraint(models.Value(1), condition=models.Q(('status', 'active')), name='uniq_active_reference_base_release'),
        ),
        migrations.AddIndex(
            model_name='referencebasereleaseaudit',
            index=models.Index(fields=['action', 'created_at'], name='addressing__action_7c36e6_idx'),
        ),
    ]
