# Generated by Django 6.0.6 on 2026-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateField()),
                ('flood', models.FloatField()),
                ('probability', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Forecasts',
                'unique_together': {('latitude', 'longitude', 'date')},
            },
        ),
    ]
