# Generated by Django 5.2 for the Aqua notification domain.
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("addressing", "0024_canonicalize_catalog_names"),
        ("flood_camera_monitoring", "0019_operational_alerts"),
        ("users", "0003_user_profile_picture_fk_and_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("endpoint", models.URLField(max_length=2048, unique=True)),
                ("p256dh", models.CharField(max_length=512)),
                ("auth", models.CharField(max_length=512)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="push_subscriptions", to="users.user")),
            ],
            options={"ordering": ["-updated_at"]},
        ),
        migrations.CreateModel(
            name="RegionSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("region", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscriptions", to="addressing.region")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="region_subscriptions", to="users.user")),
            ],
            options={"ordering": ["region__city", "region__name"]},
        ),
        migrations.CreateModel(
            name="PushDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("confirmed", "Alagamento confirmado"), ("resolved", "Alerta encerrado")], max_length=16)),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("sent", "Enviada"), ("failed", "Falhou"), ("expired", "Assinatura expirada")], db_index=True, default="pending", max_length=16)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("operational_alert", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="push_deliveries", to="flood_camera_monitoring.operationalalert")),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="notifications.pushsubscription")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.AddConstraint(
            model_name="regionsubscription",
            constraint=models.UniqueConstraint(fields=("user", "region"), name="uniq_notification_user_region"),
        ),
        migrations.AddIndex(
            model_name="pushsubscription",
            index=models.Index(fields=["user", "is_active"], name="notificatio_user_id_1159a5_idx"),
        ),
        migrations.AddConstraint(
            model_name="pushdelivery",
            constraint=models.UniqueConstraint(fields=("operational_alert", "subscription", "kind"), name="uniq_push_alert_subscription_kind"),
        ),
        migrations.AddIndex(
            model_name="pushdelivery",
            index=models.Index(fields=["status", "created_at"], name="notificatio_status_13d4c6_idx"),
        ),
    ]
