# Generated by Django 6.0.6 on 2026-07-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('occurrences', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('neighborhood', models.CharField()),
                ('rain', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('humidity', models.FloatField(null=True)),
                ('elevation', models.FloatField(null=True)),
                ('pressure', models.FloatField(null=True)),
                ('river_discharge', models.FloatField(null=True)),
                ('occurrence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrence', to='occurrences.occurrence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date', 'latitude', 'longitude', 'neighborhood'), name='unique_weather_per_day_location')],
            },
        ),
    ]
