# Generated by Django 6.0.5 on 2026-05-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_images', to='uploader.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_images', to='uploader.image'),
        ),
    ]
